version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 5
    groups:
      three:
        patterns:
          - three
          - "@types/three"
      development:
        dependency-type: development
        exclude-patterns:
          - "@types/three"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Oslo
    groups:
      github-actions:
        patterns:
          - "*"
